name: pytest
on: [push, pull_request]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10", "3.11"]
    steps:
    - uses: actions/checkout@master

    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run unit tests
      run: |
        pip install ".[dev]"
        pytest --cov=mkdocs_table_reader_plugin --cov-report=xml

    - name: Upload coverage to Codecov
      if: contains(env.USING_COVERAGE, matrix.python-version) && github.ref == 'refs/heads/master'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: true
